name: build
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
      
        working-directory: /home/runner/work/spring-web/blob/a46a1223c5e9a373011b8c32aea8f4ec9d4a2f24/gradle/wrapper/gradle-wrapper.properties
      
