name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew
      
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: 20  # Modify this to the desired Java version

      
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
