name: Gradle Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Grant execute permission to Gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      working-directory: ./spring-web
      run: ./gradlew build
